<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>topic_service_client</name>
  <version>0.0.1</version>
  <description>A ROS 2 node that subscribes to a topic and sends service requests</description>
  <maintainer email="ayushgoyal8178@gmail.com">ayuugoyal</maintainer>
  <license>Apache License 2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>example_interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
